version: '3'
services:
  graphqlcore:
    environment:
      TZ: Asia/Tokyo
      NODE_ENV: production
      VIRTUAL_HOST: graphqlcore.localhost
    build:
      context: ./graphql_core
      dockerfile: ./Dockerfile
    image: graphqlcore
    container_name: graphqlcore
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock #linux, mac
     # - //var/run/docker.sock:/var/run/docker.sock #windows
    privileged: true
  uicore:
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: uicore.localhost
    build:
      context: ./ui_core
      dockerfile: ./Dockerfile
    image: uicore
    container_name: uicore
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro #linux, mac
      #- //var/run/docker.sock:/tmp/docker.sock:ro #windows
